### ISSUE TITLE
Testcase test_batch_normalization fails on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [intel/mkl-dnn#350]
```
      Start  3: test_batch_normalization
 3/38 Test  #3: test_batch_normalization ......................***Exception: SegFault  5.92 sec
```

When run individually:
```
$ ./work/.build/tests/gtests/test_batch_normalization
[==========] Running 174 tests from 15 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from SimpleZeroDim/bnrm_test_float
[ RUN      ] SimpleZeroDim/bnrm_test_float.TestsBnrm/0
[       OK ] SimpleZeroDim/bnrm_test_float.TestsBnrm/0 (2 ms)
[ RUN      ] SimpleZeroDim/bnrm_test_float.TestsBnrm/1
[       OK ] SimpleZeroDim/bnrm_test_float.TestsBnrm/1 (1 ms)
[ RUN      ] SimpleZeroDim/bnrm_test_float.TestsBnrm/2
[       OK ] SimpleZeroDim/bnrm_test_float.TestsBnrm/2 (0 ms)
[----------] 3 tests from SimpleZeroDim/bnrm_test_float (4 ms total)

[----------] 3 tests from SimpleExpectedFails/bnrm_test_float
[ RUN      ] SimpleExpectedFails/bnrm_test_float.TestsBnrm/0
[       OK ] SimpleExpectedFails/bnrm_test_float.TestsBnrm/0 (0 ms)
[ RUN      ] SimpleExpectedFails/bnrm_test_float.TestsBnrm/1
[       OK ] SimpleExpectedFails/bnrm_test_float.TestsBnrm/1 (0 ms)
[ RUN      ] SimpleExpectedFails/bnrm_test_float.TestsBnrm/2
[       OK ] SimpleExpectedFails/bnrm_test_float.TestsBnrm/2 (0 ms)
[----------] 3 tests from SimpleExpectedFails/bnrm_test_float (0 ms total)

[----------] 4 tests from Simple_nChw16c_padded/bnrm_test_float
[ RUN      ] Simple_nChw16c_padded/bnrm_test_float.TestsBnrm/0
[       OK ] Simple_nChw16c_padded/bnrm_test_float.TestsBnrm/0 (15 ms)
[ RUN      ] Simple_nChw16c_padded/bnrm_test_float.TestsBnrm/1
[       OK ] Simple_nChw16c_padded/bnrm_test_float.TestsBnrm/1 (21 ms)
[ RUN      ] Simple_nChw16c_padded/bnrm_test_float.TestsBnrm/2
[       OK ] Simple_nChw16c_padded/bnrm_test_float.TestsBnrm/2 (151 ms)
[ RUN      ] Simple_nChw16c_padded/bnrm_test_float.TestsBnrm/3
[       OK ] Simple_nChw16c_padded/bnrm_test_float.TestsBnrm/3 (158 ms)
[----------] 4 tests from Simple_nChw16c_padded/bnrm_test_float (345 ms total)

[----------] 4 tests from Simple_nCdhw16c_padded/bnrm_test_float
[ RUN      ] Simple_nCdhw16c_padded/bnrm_test_float.TestsBnrm/0
[       OK ] Simple_nCdhw16c_padded/bnrm_test_float.TestsBnrm/0 (631 ms)
[ RUN      ] Simple_nCdhw16c_padded/bnrm_test_float.TestsBnrm/1
[       OK ] Simple_nCdhw16c_padded/bnrm_test_float.TestsBnrm/1 (771 ms)
[ RUN      ] Simple_nCdhw16c_padded/bnrm_test_float.TestsBnrm/2
[       OK ] Simple_nCdhw16c_padded/bnrm_test_float.TestsBnrm/2 (181 ms)
[ RUN      ] Simple_nCdhw16c_padded/bnrm_test_float.TestsBnrm/3
[       OK ] Simple_nCdhw16c_padded/bnrm_test_float.TestsBnrm/3 (161 ms)
[----------] 4 tests from Simple_nCdhw16c_padded/bnrm_test_float (1745 ms total)

[----------] 4 tests from Simple_nChw8c_padded/bnrm_test_float
[ RUN      ] Simple_nChw8c_padded/bnrm_test_float.TestsBnrm/0
[       OK ] Simple_nChw8c_padded/bnrm_test_float.TestsBnrm/0 (24 ms)
[ RUN      ] Simple_nChw8c_padded/bnrm_test_float.TestsBnrm/1
[       OK ] Simple_nChw8c_padded/bnrm_test_float.TestsBnrm/1 (27 ms)
[ RUN      ] Simple_nChw8c_padded/bnrm_test_float.TestsBnrm/2
[       OK ] Simple_nChw8c_padded/bnrm_test_float.TestsBnrm/2 (105 ms)
[ RUN      ] Simple_nChw8c_padded/bnrm_test_float.TestsBnrm/3
[       OK ] Simple_nChw8c_padded/bnrm_test_float.TestsBnrm/3 (65 ms)
[----------] 4 tests from Simple_nChw8c_padded/bnrm_test_float (222 ms total)

[----------] 8 tests from Simple_nCdhw16c/bnrm_test_float
[ RUN      ] Simple_nCdhw16c/bnrm_test_float.TestsBnrm/0
[       OK ] Simple_nCdhw16c/bnrm_test_float.TestsBnrm/0 (22 ms)
[ RUN      ] Simple_nCdhw16c/bnrm_test_float.TestsBnrm/1
[       OK ] Simple_nCdhw16c/bnrm_test_float.TestsBnrm/1 (31 ms)
[ RUN      ] Simple_nCdhw16c/bnrm_test_float.TestsBnrm/2
[       OK ] Simple_nCdhw16c/bnrm_test_float.TestsBnrm/2 (148 ms)
[ RUN      ] Simple_nCdhw16c/bnrm_test_float.TestsBnrm/3
[       OK ] Simple_nCdhw16c/bnrm_test_float.TestsBnrm/3 (131 ms)
[ RUN      ] Simple_nCdhw16c/bnrm_test_float.TestsBnrm/4
[       OK ] Simple_nCdhw16c/bnrm_test_float.TestsBnrm/4 (575 ms)
[ RUN      ] Simple_nCdhw16c/bnrm_test_float.TestsBnrm/5
[       OK ] Simple_nCdhw16c/bnrm_test_float.TestsBnrm/5 (626 ms)
[ RUN      ] Simple_nCdhw16c/bnrm_test_float.TestsBnrm/6
[       OK ] Simple_nCdhw16c/bnrm_test_float.TestsBnrm/6 (98 ms)
[ RUN      ] Simple_nCdhw16c/bnrm_test_float.TestsBnrm/7
[       OK ] Simple_nCdhw16c/bnrm_test_float.TestsBnrm/7 (79 ms)
[----------] 8 tests from Simple_nCdhw16c/bnrm_test_float (1712 ms total)

[----------] 8 tests from Simple_nCdhw8c/bnrm_test_float
[ RUN      ] Simple_nCdhw8c/bnrm_test_float.TestsBnrm/0
[       OK ] Simple_nCdhw8c/bnrm_test_float.TestsBnrm/0 (22 ms)
[ RUN      ] Simple_nCdhw8c/bnrm_test_float.TestsBnrm/1
[       OK ] Simple_nCdhw8c/bnrm_test_float.TestsBnrm/1 (31 ms)
[ RUN      ] Simple_nCdhw8c/bnrm_test_float.TestsBnrm/2
[       OK ] Simple_nCdhw8c/bnrm_test_float.TestsBnrm/2 (107 ms)
[ RUN      ] Simple_nCdhw8c/bnrm_test_float.TestsBnrm/3
[       OK ] Simple_nCdhw8c/bnrm_test_float.TestsBnrm/3 (113 ms)
[ RUN      ] Simple_nCdhw8c/bnrm_test_float.TestsBnrm/4
[       OK ] Simple_nCdhw8c/bnrm_test_float.TestsBnrm/4 (529 ms)
[ RUN      ] Simple_nCdhw8c/bnrm_test_float.TestsBnrm/5
[       OK ] Simple_nCdhw8c/bnrm_test_float.TestsBnrm/5 (602 ms)
[ RUN      ] Simple_nCdhw8c/bnrm_test_float.TestsBnrm/6
[       OK ] Simple_nCdhw8c/bnrm_test_float.TestsBnrm/6 (78 ms)
[ RUN      ] Simple_nCdhw8c/bnrm_test_float.TestsBnrm/7
[       OK ] Simple_nCdhw8c/bnrm_test_float.TestsBnrm/7 (93 ms)
[----------] 8 tests from Simple_nCdhw8c/bnrm_test_float (1577 ms total)

[----------] 4 tests from Simple_NC/bnrm_test_float
[ RUN      ] Simple_NC/bnrm_test_float.TestsBnrm/0
[       OK ] Simple_NC/bnrm_test_float.TestsBnrm/0 (1 ms)
[ RUN      ] Simple_NC/bnrm_test_float.TestsBnrm/1
[       OK ] Simple_NC/bnrm_test_float.TestsBnrm/1 (1 ms)
[ RUN      ] Simple_NC/bnrm_test_float.TestsBnrm/2
[       OK ] Simple_NC/bnrm_test_float.TestsBnrm/2 (1 ms)
[ RUN      ] Simple_NC/bnrm_test_float.TestsBnrm/3
[       OK ] Simple_NC/bnrm_test_float.TestsBnrm/3 (1 ms)
[----------] 4 tests from Simple_NC/bnrm_test_float (5 ms total)

[----------] 4 tests from Simple_NCDHW/bnrm_test_float
[ RUN      ] Simple_NCDHW/bnrm_test_float.TestsBnrm/0
[       OK ] Simple_NCDHW/bnrm_test_float.TestsBnrm/0 (1 ms)
[ RUN      ] Simple_NCDHW/bnrm_test_float.TestsBnrm/1
[       OK ] Simple_NCDHW/bnrm_test_float.TestsBnrm/1 (1 ms)
[ RUN      ] Simple_NCDHW/bnrm_test_float.TestsBnrm/2
Segmentation fault
```

In debugger:
```
(gdb) bt
#0  0x0000000801b17bfa in mkldnn::impl::cpu::ncsp_batch_normalization_bwd_t::execute_backward()::$_1::operator()(int, int) const () from /usr/ports/math/mkl-dnn/work/.build/
src/libmkldnn.so.0
#1  0x0000000801b181a2 in .omp_outlined..259 () from /usr/ports/math/mkl-dnn/work/.build/src/libmkldnn.so.0
#2  0x0000000801efdbc3 in __kmp_invoke_microtask () from /usr/local/lib/libomp.so
#3  0x0000000801ec60db in ?? () from /usr/local/lib/libomp.so
#4  0x0000000801ec5582 in ?? () from /usr/local/lib/libomp.so
#5  0x0000000801ef166b in ?? () from /usr/local/lib/libomp.so
#6  0x0000000802a56026 in thread_start (curthread=0x803419200) at /usr/src/lib/libthr/thread/thr_create.c:290
#7  0x0000000000000000 in ?? ()
```

FreeBSD 11.2 amd64.
mkl-dnn is built from the FreeBSD port.
OpenMP is used.

**Comment by rsdubtso** [comment]
@yurivict: unfortunately MKL-DNN does not support FreeBSD and we have no resources or plans to. But patches are always welcome. Can you reproduce this issue with a debug build and fill all the fields in the issue template?

**Comment by rsdubtso** [comment]
Closing because of lack of activity. Please feel free to reopen.

**Comment by yurivict** [comment]
@rsdubtso 
```test_layer_normalization``` doesn't fail when built with debug.

I build with clang-9 on FreeBSD. Maybe you can build it with clang on Linux and reproduce the problem.
